### ISSUE TITLE
Not working with babel 7.0.0-rc.1

### ISSUE THREAD

**Issue by benoitmaudet** [GoogleChromeLabs/preload-webpack-plugin#75]
Hello,

The plugin does not work anymore with babel 7.0.0-rc...

Error: Cannot find module '@babel/runtime/core-js/get-iterator'

**Comment by jeffposnick** [comment]
- Are you using the `v3` branch?
- How are you ending up with that version of babel? Are you manually modifying the `package.json`?

**Comment by benoitmaudet** [comment]
I've just tried with v3 branch, I've got the same error : 
```
D:\react-test\node_modules\webpack-cli\bin\cli.js:244
info				throw err;
 Visit 				^
https://yarnpkg.com/en/docs/cli/run
Error: Cannot find module '@babel/runtime/core-js/get-iterator'
 for documentation about this command.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (D:\react-test\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\react-test\node_modules\preload-webpack-plugin\build\index.js:5:44)
    at Module._compile (D:\react-test\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (D:\react-test\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\react-test\webpack.prod.config.js:4:30)
    at Module._compile (D:\react-test\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (D:\react-test\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (D:\react-test\node_modules\webpack-cli\bin\convert-argv.js:133:13)
    at requireConfig (D:\react-test\node_modules\webpack-cli\bin\convert-argv.js:135:6)
    at D:\react-test\node_modules\webpack-cli\bin\convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (D:\react-test\node_modules\webpack-cli\bin\convert-argv.js:140:15)
    at yargs.parse (D:\react-test\node_modules\webpack-cli\bin\cli.js:241:39)
    at Object.parse (D:\react-test\node_modules\webpack-cli\node_modules\yargs\yargs.js:563:18)
    at D:\react-test\node_modules\webpack-cli\bin\cli.js:219:8
    at Object.<anonymous> (D:\react-test\node_modules\webpack-cli\bin\cli.js:530:3)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
error Command failed with exit code 1.

```

Yes, I've upgraded my `package.json` to the last version of babel for testing : 
```json
 "dependencies": {
    "@babel/polyfill": "^7.0.0-rc.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.2",
    "@fortawesome/free-brands-svg-icons": "^5.2.0",
    "@fortawesome/free-regular-svg-icons": "^5.2.0",
    "@fortawesome/free-solid-svg-icons": "^5.2.0",
    "@fortawesome/react-fontawesome": "^0.1.1",
    "brace": "^0.11.1",
    "highlight.js": "^9.12.0",
    "history": "^4.7.2",
    "http-server": "^0.11.1",
    "moment": "^2.22.2",
    "prop-types": "^15.6.2",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "react-markdown": "^3.4.1",
    "react-popper": "^1.0.0",
    "react-redux": "^5.0.7",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "react-router-redux": "^5.0.0-alpha.9",
    "react-select": "^2.0.0-beta.7",
    "react-table": "^6.8.6",
    "react-test-renderer": "^16.4.2",
    "react-transition-group": "^2.4.0",
    "reactstrap": "^6.3.1",
    "redux": "^4.0.0",
    "redux-saga": "^0.16.0",
    "validator": "^10.5.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0-rc.1",
    "@babel/plugin-proposal-class-properties": "^7.0.0-rc.1",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0-rc.1",
    "@babel/plugin-syntax-import-meta": "^7.0.0-rc.1",
    "@babel/preset-env": "^7.0.0-rc.1",
    "@babel/preset-react": "^7.0.0-rc.1",
    "@babel/runtime": "^7.0.0-rc.1",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^23.4.2",
    "babel-loader": "^8.0.0-beta.4",
    "babel-plugin-react-css-modules": "^3.4.2",
    "babel-plugin-transform-do-expressions": "^7.0.0-beta.3",
    "babel-plugin-transform-function-bind": "^7.0.0-beta.3",
    "babel-plugin-transform-imports": "^1.5.0",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.14",
    "brotli-webpack-plugin": "^1.0.0",
    "compression-webpack-plugin": "^1.1.11",
    "css-loader": "^1.0.0",
    "enzyme": "^3.4.1",
    "enzyme-adapter-react-16": "^1.2.0",
    "expect": "^23.5.0",
    "file-loader": "^1.1.11",
    "html-webpack-plugin": "^3.2.0",
    "jest": "^23.5.0",
    "jest-css-modules": "^1.1.0",
    "mini-css-extract-plugin": "^0.4.1",
    "preload-webpack-plugin": "^3.0.0-beta.1",
    "prettier": "^1.14.2",
    "react-ace": "^6.1.4",
    "style-loader": "^0.22.1",
    "url-loader": "^1.0.1",
    "webpack": "^4.16.5",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-bundle-tracker": "^0.3.0",
    "webpack-cli": "^3.1.0",
    "webpack-dev-server": "^3.1.5"
  },
```

**Comment by benoitmaudet** [comment]
It works, thank you !
